### PR TITLE
Update to node 20, cache and core to latest versions

### PR DESCRIPTION
**Pull request by Hermanverschooten**
I updated the node version as specified in the documentation.
I also updated the core and cache dependencies, but I don't know how to test if this still works.

### CODE REVIEW

**Comment by mpizenberg** [comment]
Thanks! I have an action that triggers on push, so we'll know when it's merged. I should have added on PR :facepalm: 

BTW, action core dep did not change in the package json. Is there a forgotten commit?

**Comment by mpizenberg** [comment]
Maybe if you update the gh action of this repo to also trigger on pr it will work.

**Comment by Hermanverschooten** [comment]
I updated the workflow

**Comment by mpizenberg** [comment]
Seems like it all worked :) Thanks for the update, I'll publish an updated action in the weekend.

**Pull request merged**
